### ISSUE TITLE
Support iOS 8.0

### ISSUE THREAD

**Issue by jacks8x** [NitWitStudios/NWSTokenView#19]
Does this library support iOS 8.0, after i install this library in my project support 8.0 it will get error like the code did not convert to swift 3
If I change my project development target to 9.0 it's ok

**Comment by ghost** [comment]
@jacks8x I have lowered the base to iOS 8 and fixed some of the Swift 3 warnings. Please try updating your pod and project. Cheer! 🍻

**Comment by ghost** [comment]
Sorry about that, missed one other thing. Please use v2.0.3 and let me know if you have any problems. Cheers! 🍻
