### ISSUE TITLE
Tokenview scrollview issue.

### ISSUE THREAD

**Issue by avinashyalgonde** [NitWitStudios/NWSTokenView#23]
Select same entries from list and type 'com'. Hit backspace to remove characters. When last char('c') is removed, scrollview doesn't retain its position.

![simulator screen shot 15-nov-2017 4 02 25 pm](https://user-images.githubusercontent.com/22027273/32831979-094cc188-ca20-11e7-8534-e3c1ccacf2e9.png)

**Comment by JimmyJammed** [comment]
@avinashyalgonde  Sorry for delay, but haven't been able to maintain this library for some time now. If you are willing to make the fix and create a Pull Request, I will happily review and merge in.
Cheers! 🍻
