### ISSUE TITLE
Rotation listener when there is no datasource crashes

### ISSUE THREAD

**Issue by oteronavarretericardo** [NitWitStudios/NWSTokenView#24]
<img width="1440" alt="screen shot 2018-01-22 at 1 01 00 pm" src="https://user-images.githubusercontent.com/14191619/35244275-7cf89eac-ff74-11e7-8531-f696d14d2527.png">
<img width="1440" alt="screen shot 2018-01-22 at 1 00 52 pm" src="https://user-images.githubusercontent.com/14191619/35244276-7d1e951c-ff74-11e7-8db3-b749a84b777a.png">

The issue is really simple, forced unwrapping

**Comment by ghost** [comment]
Thanks for bringing to our attention. If you are willing to make the fix and create a PR we can merge that in for you.
Cheers! 🍻
